## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

# CONTAINER_TOOL defines the container tool to be used for building images.
CONTAINER_TOOL ?= docker

# Image URL to use for building/pushing image targets
IMG ?= ghcr.io/openeverest/provider-kserve-dev:latest

# controller-gen version
CONTROLLER_TOOLS_VERSION ?= v0.18.0
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen-$(CONTROLLER_TOOLS_VERSION)

# yq version for YAML processing
YQ_VERSION ?= v4.44.6
YQ ?= $(LOCALBIN)/yq-$(YQ_VERSION)

# golangci-lint version
GOLANGCI_LINT_VERSION ?= v2.12.2
GOLANGCI_LINT ?= $(LOCALBIN)/golangci-lint-$(GOLANGCI_LINT_VERSION)

# Helm chart directory
CHART_DIR ?= charts/provider-kserve

# Local KServe charts checkout used only by sync-llm-presets. Override to
# point at a different checkout. The KServe CRDs are vendored into the chart's
# crds/ directory by sync-kserve-crds (pulled from the KServe OCI registry).
KSERVE_CHARTS ?= ../kserve/charts

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: run
run: generate ## Run the provider locally.
	go run cmd/provider/main.go

.PHONY: lint
lint: golangci-lint ## Run golangci-lint.
	$(GOLANGCI_LINT) run

.PHONY: test
test: ## Run unit tests.
	go test ./... -coverprofile cover.out

##@ Code Generation

.PHONY: manifests
manifests: controller-gen ## Generate RBAC manifests using controller-gen from kubebuilder markers.
	$(CONTROLLER_GEN) rbac:roleName=manager-role paths="./..." output:rbac:dir=config/rbac
	@{ \
		echo '# This file is generated by controller-gen from kubebuilder RBAC markers.'; \
		echo '# Do not edit manually. Run `make manifests` to regenerate.'; \
		echo '#'; \
		echo '# Source markers are in internal/provider/rbac.go and other .go files'; \
		echo '# with +kubebuilder:rbac annotations.'; \
		if grep -q '^---' config/rbac/role.yaml; then sed -n '/^---/,$$p' config/rbac/role.yaml; else cat config/rbac/role.yaml; fi; \
	} > config/rbac/role.yaml.tmp
	@mv config/rbac/role.yaml.tmp config/rbac/role.yaml

.PHONY: helm-sync-rbac
helm-sync-rbac: yq ## Sync generated RBAC rules into the Helm chart.
	@echo "Syncing RBAC rules from config/rbac/role.yaml to Helm chart..."
	@{ \
		echo '# This file is generated by `make helm-sync-rbac` from config/rbac/role.yaml.'; \
		echo '# Do not edit manually. Run `make generate` to update.'; \
		$(YQ) '.rules' config/rbac/role.yaml; \
	} > $(CHART_DIR)/generated/rbac-rules.yaml
	@echo "Done."

.PHONY: sync-llm-presets
sync-llm-presets: ## Vendor the KServe LLM preset configs into the chart from $(KSERVE_CHARTS).
	@if [ ! -f "$(KSERVE_CHARTS)/kserve-runtime-configs/files/llmisvcconfigs/resources.yaml" ]; then \
		echo "KSERVE_CHARTS not found at $(KSERVE_CHARTS); keeping existing vendored LLM presets in $(CHART_DIR)/files/llmisvcconfigs/"; \
		if [ ! -f "$(CHART_DIR)/files/llmisvcconfigs/resources.yaml" ]; then \
			echo "ERROR: $(CHART_DIR)/files/llmisvcconfigs/resources.yaml is missing. Restore from git or clone KServe next to this repo."; \
			exit 1; \
		fi; \
	else \
		echo "Syncing KServe LLM preset configs from $(KSERVE_CHARTS) into $(CHART_DIR)/files/..."; \
		mkdir -p $(CHART_DIR)/files/llmisvcconfigs; \
		cp $(KSERVE_CHARTS)/kserve-runtime-configs/files/llmisvcconfigs/resources.yaml $(CHART_DIR)/files/llmisvcconfigs/resources.yaml; \
		echo "Done."; \
	fi

.PHONY: sync-dashboards
sync-dashboards: ## Copy Grafana dashboard JSON from docs/ into the Helm chart.
	@echo "Syncing Grafana dashboards from docs/dashboards/ into $(CHART_DIR)/files/dashboards/..."
	@mkdir -p $(CHART_DIR)/files/dashboards
	@cp docs/dashboards/vllm.json docs/dashboards/gateway.json $(CHART_DIR)/files/dashboards/
	@echo "Done."

.PHONY: generate
generate: manifests helm-sync-rbac sync-llm-presets sync-dashboards ## Run all code generation (RBAC + Helm sync + LLM presets + dashboards + provider spec from definition/).
	go generate ./...
	@echo "All generation complete."

.PHONY: verify
verify: ## Verify that generated files are up-to-date (for CI).
	@$(MAKE) generate
	@if git diff --quiet -- config/ $(CHART_DIR)/generated/ $(CHART_DIR)/files/; then \
		echo "Generated files are up-to-date."; \
	else \
		echo "ERROR: Generated files are out of date. Run 'make generate' and commit the changes."; \
		git diff -- config/ $(CHART_DIR)/generated/ $(CHART_DIR)/files/; \
		exit 1; \
	fi

##@ Build

.PHONY: build
build: generate ## Build provider binary.
	go build -o bin/provider cmd/provider/main.go

.PHONY: docker-build
docker-build: ## Build docker image.
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image.
	$(CONTAINER_TOOL) push ${IMG}

##@ Helm

# KServe CRD charts, vendored into the chart's crds/ directory by
# sync-kserve-crds. They are NOT tracked as subchart dependencies: Helm applies
# crds/ before rendering templates, so a single `helm install` can create the
# CRs this chart ships (ClusterServingRuntime, ClusterStorageContainer,
# LLMInferenceServiceConfig) without a two-phase install. Version follows the
# KServe controller charts pinned in Chart.yaml.
KSERVE_CRD_CHARTS ?= kserve-crd kserve-llmisvc-crd

.PHONY: helm-deps
helm-deps: yq sync-kserve-crds ## Download/update Helm chart dependencies.
	helm repo add jetstack https://charts.jetstack.io >/dev/null 2>&1 || true
	helm repo update jetstack >/dev/null 2>&1 || true
	helm dependency update $(CHART_DIR)

.PHONY: sync-kserve-crds
sync-kserve-crds: yq ## Vendor the KServe CRDs into the chart's crds/ directory.
	@ver=$$($(YQ) '.dependencies[] | select(.name == "kserve-resources") | .version' $(CHART_DIR)/Chart.yaml); \
	echo "Vendoring KServe CRDs ($$ver) into $(CHART_DIR)/crds..."; \
	rm -rf $(CHART_DIR)/crds $(CHART_DIR)/.crd-src; \
	mkdir -p $(CHART_DIR)/crds $(CHART_DIR)/.crd-src; \
	for c in $(KSERVE_CRD_CHARTS); do \
		helm pull oci://ghcr.io/kserve/charts/$$c --version $$ver --untar --untardir $(CHART_DIR)/.crd-src >/dev/null; \
		for f in $(CHART_DIR)/.crd-src/$$c/templates/*.yaml; do \
			[ -e "$$f" ] || continue; \
			grep -q '{{' "$$f" || cp "$$f" $(CHART_DIR)/crds/; \
		done; \
		if [ -d "$(CHART_DIR)/.crd-src/$$c/files" ]; then \
			cp $(CHART_DIR)/.crd-src/$$c/files/*.yaml $(CHART_DIR)/crds/ 2>/dev/null || true; \
		fi; \
	done; \
	rm -rf $(CHART_DIR)/.crd-src; \
	echo "Done."

.PHONY: helm-install
helm-install: helm-deps ## Install the provider using Helm.
	helm install provider-kserve $(CHART_DIR) --create-namespace

.PHONY: helm-upgrade
helm-upgrade: helm-deps ## Upgrade the provider using Helm.
	helm upgrade provider-kserve $(CHART_DIR)

.PHONY: helm-uninstall
helm-uninstall: ## Uninstall the provider using Helm.
	helm uninstall provider-kserve

.PHONY: helm-template
helm-template: helm-deps ## Render Helm chart templates locally (dry-run).
	helm template provider-kserve $(CHART_DIR)

##@ Testing

.PHONY: test-reconcile
test-reconcile: ## Run the fast reconcile tests (chainsaw) against a running cluster.
	. ./test/vars.sh && chainsaw test --config ./test/reconcile/.chainsaw.yaml ./test/reconcile

.PHONY: test-e2e
test-e2e: ## Run the e2e tests (chainsaw). Slow: real models, real serving.
	. ./test/vars.sh && chainsaw test --config ./test/e2e/.chainsaw.yaml ./test/e2e

##@ Local Development Cluster

.PHONY: k3d-cluster-up
k3d-cluster-up: ## Create a local k3d cluster for development.
	$(info Creating k3d cluster for testing)
	k3d cluster create --config ./dev/k3d_config.yaml

.PHONY: k3d-cluster-down
k3d-cluster-down: ## Delete the local k3d cluster.
	$(info Destroying k3d test cluster)
	k3d cluster delete --config ./dev/k3d_config.yaml

.PHONY: k3d-cluster-reset
k3d-cluster-reset: k3d-cluster-down k3d-cluster-up ## Reset the local k3d cluster.

##@ Tilt Development

.PHONY: dev-up
dev-up: k3d-cluster-up ## Create the k3d cluster and start the Tilt dev environment.
	tilt up -f dev/Tiltfile

.PHONY: dev-down
dev-down: ## Stop the Tilt dev environment (keeps the cluster).
	tilt down -f dev/Tiltfile

.PHONY: dev-destroy
dev-destroy: k3d-cluster-down ## Stop Tilt and delete the k3d cluster.

##@ Tool Dependencies

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Install controller-gen.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: yq
yq: $(YQ) ## Install yq.
$(YQ): $(LOCALBIN)
	@echo "Installing yq $(YQ_VERSION)..."
	@GOBIN=$(LOCALBIN) go install github.com/mikefarah/yq/v4@$(YQ_VERSION) && mv $(LOCALBIN)/yq $(YQ)

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Install golangci-lint.
$(GOLANGCI_LINT): $(LOCALBIN)
	$(call go-install-tool,$(GOLANGCI_LINT),github.com/golangci/golangci-lint/v2/cmd/golangci-lint,$(GOLANGCI_LINT_VERSION))

# go-install-tool will 'go install' any package with custom target and target name. Usage:
# $(call go-install-tool,<target>,<package>,<version>)
define go-install-tool
@[ -f $(1) ] || { \
set -e; \
package=$(2)@$(3); \
echo "Installing $${package}"; \
GOBIN=$(LOCALBIN) go install $${package}; \
mv -f $$(echo "$(1)" | sed "s/-$(3)$$//") $(1); \
}
endef
